from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
     path('add-animal', views.addAnimal, name='add_animal'),
     path('update-animal/<int:id>', views.updateAnimal, name='update_animal'),
     path('delete-animal/<int:id>', views.deleteAnimal, name='delete_animal'),
     path('profile/<str:username>', views.userProfile, name='user_profile'),
     path('activity/upload-history/<str:username>', views.uploadHistory, name='upload_history'),
     path('activity/order-history/<str:username>', views.order_history, name='order_history'),
     path('activity/request-history/<str:username>', views.request_history, name='request_history'),
     path('admin-dashboard', views.adminDashboard, name='admin_dashboard'),
     path('user-dashboard', views.userDashboard, name='user_dashboard'),
     path('manage-animals', views.manageAnimals, name='manage_animals'),
     path('approve-upload/<int:id>', views.approveAnimal, name='approve_upload'),
     path('approved-uploads', views.approved_uploads, name='approved_uploads'),
     path('manage-accessories', views.manageAccessories, name='manage_accessories'),
     path('add-accessory', views.addAccessory, name='add_accessory'),
     path('update-accessory/<int:id>', views.updateAccessory, name='update_accessory'),
     path('delete-accessory/<int:id>', views.deleteAccessory, name='delete_accessory'),
     path('catalog/animal/for_adoption', views.animalsForAdoption, name='animals_for_adoption'),
     path('catalog/animal/for_daycare', views.animalsForDaycare, name='animals_for_daycare'),
     path('catalog/product/for_sale', views.productsForSale, name='products_for_sale'),
     path('animal/<int:id>/', views.animal_detail, name='animal_detail'),
     path('update-password', views.change_password, name='change_password'),
     path('create-ticket', views.create_ticket, name='create_ticket'),
     path('ticket/<int:ticket_id>', views.ticket_detail, name='ticket_detail'),
     path('ticket/<int:ticket_id>/message', views.add_message, name='add_message'),
     path('ticket-list', views.list_tickets, name='list_tickets'),
     path('ticket/<int:ticket_id>/accept/', views.accept_ticket, name='accept_ticket'),
     path('ticket/<int:ticket_id>/assign/', views.assign_ticket, name='assign_ticket'),
     path('ticket/<int:ticket_id>/close/', views.close_ticket, name='close_ticket'),
     # path('ticket/<int:ticket_id>/reopen/', views.reopen_ticket, name='reopen_ticket'),
     path('ticket/<ticket_id>/delete/', views.decline_ticket, name='decline_ticket'),
     path('cart/add/<int:accessory_id>/', views.add_to_cart, name='add_to_cart'),
     path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
     path('cart/adjust/<int:item_id>/<str:action>/', views.adjust_cart_item, name='adjust_cart_item'),
     path('cart/', views.cart_view, name='cart'),
     path('product/<int:pk>/', views.product_detail, name='product_detail'),
     path('place-order/', views.place_order, name='place_order'),
     path('order-status/<str:order_id>/', views.order_status, name='order_status'),
     path('create-stripe-session/<order_id>/', views.create_stripe_session, name='create_stripe_session'),
     path('payment-success/<order_id>/', views.payment_success, name='payment_success'),
     path('payment-cancel/<order_id>/', views.payment_cancel, name='payment_cancel'),
     path('webhooks/stripe/', views.stripe_webhook, name='stripe_webhook'),
     path('animal-info/', views.animal_info, name='animal_info'),
     path('know-before/', views.know_before, name='know_before'),
     path('know-before-cat/', views.know_before_cat, name='know_before_cat'),
     path('know-before-dog/', views.know_before_dog, name='know_before_dog'),
     path('order-history/<str:username>', views.order_history, name='order_history'),
     path('cancel-order/<str:order_id>', views.cancel_order, name='cancel_order'),
     path('request-animal/<int:id>', views.request_animal, name='request_animal'),
     path('cancel-request/<str:request_id>', views.cancel_request, name='cancel_request'),
     path('complete-request/<str:request_id>', views.complete_request, name='complete_request'),
     path('catalog', views.catalog, name='catalog'),
     path('manage-orders', views.manage_orders, name='manage_orders'),
     path('update-order/<str:order_id>', views.update_order, name='update_order'),
     path('notifications/', views.get_notifications, name='get_notifications'),
     path('notifications/all', views.notification_list, name='notification_list'),
     path('notifications/mark-as-read/<int:notification_id>/', views.mark_notification_as_read, name='mark_as_read'),
     path('unread-count/', views.unread_count, name='unread_count'),
     path('notifications/mark-all-as-read/', views.mark_all_as_read, name='mark_all_as_read'),
     path('chat/<str:request_id>/', views.chat_room, name='chat_room'),
     path('chat/close/<str:request_id>/', views.close_chat, name='close_chat'),
     path('active-requests', views.active_requests, name='active_requests'),
     path('completed-orders', views.completed_orders, name='completed_orders'),
     path('completed-requests', views.completed_requests, name='completed_requests'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)