# Generated by Django 5.0.2 on 2024-03-19 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='accessory_pictures/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_by_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
