# Generated by Django 4.1 on 2024-02-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_profile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
