# Generated by Django 4.2.10 on 2024-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0003_accessories_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
