# Generated by Django 4.2.10 on 2024-03-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0004_room"),
    ]

    operations = [
        migrations.RenameModel(old_name="Room", new_name="Support",),
    ]
