# Generated by Django 5.0.2 on 2024-03-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="contact_info",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="post_pictures/"),
        ),
    ]
