# Generated by Django 4.2.10 on 2024-03-26 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0005_rename_room_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="adopted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adopted_animals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_animals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
