# Generated by Django 5.0.2 on 2024-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseapp", "0005_post_contact_info_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
