# Generated by Django 5.0.2 on 2024-03-26 03:56

import baseapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_rename_uploaded_by_animal_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=baseapp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='animal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=baseapp.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
