# Generated by Django 5.0.2 on 2024-03-26 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_alter_animal_picture_alter_animal_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='user_identifier',
        ),
        migrations.AlterField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
